### ISSUE TITLE
Tracking issue for supported Minion constraints

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#171]
This issue tracks support for Minion constraints across all levels of the project and related tasks.

## By Constraint

<details>
<summary>
<h3>minion_rs</h3>
</summary>

- [x] #438
- [x] #455
- [x] watched-or
- [ ] eq
- [x] ineq
- [ ] min
- [ ] max
- [ ] difference
- [x] div_undefzero
- [ ] modulo_undefzero
- [ ] pow
- [ ] product
- [ ] weightedsumgeq
- [x] weightedsumleq
- [ ] check[assign]
- [ ] check[gsa]
- [ ] forwardchecking
- [ ] reify
- [ ] reifyimply
- [ ] reifyimply-quick
- [ ] gacalldiff
- [ ] alldiff
- [ ] alldiffmatrix
- [ ] watchsumgeq
- [ ] watchsumleq
- [ ] occurrencegeq
- [ ] occurrenceleq
- [ ] occurrence
- [ ] litsumgeq
- [ ] gcc
- [ ] gccweak
- [ ] lexleq[rv]
- [ ] lexleq
- [ ] lexless
- [ ] lexleq[quick]
- [ ] lexless[quick]
- [ ] watchvecneq
- [ ] watchvecexists_less
- [ ] hamming
- [ ] not-hamming
- [x] ~~frameupdate~~
- [ ] haggisgac
- [ ] haggisgac-stable
- [ ] shortstr2
- [ ] shortctuplestr2
- [ ] negativetable
- [ ] table
- [ ] gacschema
- [ ] lighttable
- [ ] mddc
- [ ] negativemddc
- [ ] str2plus
- [ ] nvaluegeq
- [ ] nvalueleq
- [x] sumgeq
- [x] sumleq
- [ ] element
- [ ] element_one
- [ ] element_undefzero
- [ ] watchelement
- [ ] watchelement_one
- [ ] watchelement_one_undefzero
- [ ] watchelement_undefzero
- [ ] w-literal
- [ ] w-notliteral
- [ ] w-inintervalset
- [ ] w-inrange
- [ ] w-inset
- [ ] w-notinrange
- [ ] w-notinset
- [ ] abs
- [ ] diseq
- [ ] minuseq
- [ ] gaceq
- [ ] watchless
- [ ] watchneq
- [x] ~~true~~
- [x] ~~false~~
- [x] ~~()()collectevents()()~~
- [x] ~~__reify_diseq~~
- [x] ~~__reify_eq~~
- [x] ~~__reify_minuseq~~

</details>

---

<details>

<summary>

<h3>Solver Adaptor</h3>

</summary>

- [x] watched-and
- [x] watched-or
- [ ] eq
- [x] ineq
- [ ] min
- [ ] max
- [x] difference
- [x] div_undefzero
- [x] modulo_undefzero
- [ ] pow
- [x] product
- [x] weightedsumgeq
- [x] weightedsumleq
- [ ] check[assign]
- [ ] check[gsa]
- [ ] forwardchecking
- [ ] reify
- [ ] reifyimply
- [ ] reifyimply-quick
- [ ] gacalldiff
- [ ] alldiff
- [ ] alldiffmatrix
- [ ] watchsumgeq
- [ ] watchsumleq
- [ ] occurrencegeq
- [ ] occurrenceleq
- [ ] occurrence
- [ ] litsumgeq
- [ ] gcc
- [ ] gccweak
- [ ] lexleq[rv]
- [ ] lexleq
- [ ] lexless
- [ ] lexleq[quick]
- [ ] lexless[quick]
- [ ] watchvecneq
- [ ] watchvecexists_less
- [ ] hamming
- [ ] not-hamming
- [ ] ~~frameupdate~~
- [ ] haggisgac
- [ ] haggisgac-stable
- [ ] shortstr2
- [ ] shortctuplestr2
- [ ] negativetable
- [ ] table
- [ ] gacschema
- [ ] lighttable
- [ ] mddc
- [ ] negativemddc
- [ ] str2plus
- [ ] nvaluegeq
- [ ] nvalueleq
- [x] sumgeq
- [x] sumleq
- [ ] element
- [ ] element_one
- [ ] element_undefzero
- [ ] watchelement
- [ ] watchelement_one
- [ ] watchelement_one_undefzero
- [ ] watchelement_undefzero
- [x] w-literal
- [ ] w-notliteral
- [ ] w-inintervalset
- [ ] w-inrange
- [ ] w-inset
- [ ] w-notinrange
- [ ] w-notinset
- [ ] abs
- [x] diseq
- [x] minuseq
- [ ] gaceq
- [ ] watchless
- [ ] watchneq
- [x] ~~true~~
- [x] ~~false~~
- [x] ~~()()collectevents()()~~
- [x] ~~__reify_diseq~~
- [x] ~~__reify_eq~~
- [x] ~~__reify_minuseq~~

</details>

---

### Rules / integration tests

**Success criteria:** We can convert from `eprime` to these constraints, and have integration tests specifically targeting the minion constraint:

See `integration/minion_constraints`.

- [x] #456
- [x] div_undefzero
- [x] watched-and
- [x] watched-or
- [x] #490
- [x] #505 
- [ ] eq
- [ ] ineq
- [ ] min
- [ ] max
- [ ] difference
- [x] pow
- [x] product
- [x] weightedsumgeq
- [x] weightedsumleq
- [ ] check[assign]
- [ ] check[gsa]
- [ ] forwardchecking
- [ ] reify
- [ ] reifyimply
- [ ] reifyimply-quick
- [ ] gacalldiff
- [ ] alldiff
- [ ] alldiffmatrix
- [ ] watchsumgeq
- [ ] watchsumleq
- [ ] occurrencegeq
- [ ] occurrenceleq
- [ ] occurrence
- [ ] litsumgeq
- [ ] gcc
- [ ] gccweak
- [ ] lexleq[rv]
- [ ] lexleq
- [ ] lexless
- [ ] lexleq[quick]
- [ ] lexless[quick]
- [ ] watchvecneq
- [ ] watchvecexists_less
- [ ] hamming
- [ ] not-hamming
- [ ] ~~frameupdate~~
- [ ] haggisgac
- [ ] haggisgac-stable
- [ ] shortstr2
- [ ] shortctuplestr2
- [ ] negativetable
- [ ] table
- [ ] gacschema
- [ ] lighttable
- [ ] mddc
- [ ] negativemddc
- [ ] str2plus
- [ ] nvaluegeq
- [ ] nvalueleq
- [x] sumgeq
- [x] sumleq
- [ ] element
- [ ] element_one
- [ ] element_undefzero
- [ ] watchelement
- [ ] watchelement_one
- [ ] watchelement_one_undefzero
- [ ] watchelement_undefzero
- [x] w-literal
- [ ] w-notliteral
- [ ] w-inintervalset
- [ ] w-inrange
- [ ] w-inset
- [ ] w-notinrange
- [ ] w-notinset
- [ ] abs
- [x] diseq
- [x] minuseq
- [ ] gaceq
- [ ] watchless
- [ ] watchneq
- [x] true
- [x] false

## Other Tasks

- [x] #454
- [ ] #240 
- [ ] #243

## See also

* https://minion-solver.readthedocs.io/en/latest/usage/constraints.html

**Comment by niklasdewally** [comment]
@ChrisJefferson Are any of these internal or obviously not useful for us? (__refiy_?)

**Comment by ozgurakgun** [comment]
We probably don't need false and true, in addition to the the ones you mention.

**Comment by niklasdewally** [comment]
Might not need frame update.

**Comment by niklasdewally** [comment]
CC @EEJDempster @ozgurakgun.

Resurrecting this issue to track Minion rule implementation and the associated integration tests in `minion_constraints`

Feel free to add to the above task list as you see fit.

**Comment by niklasdewally** [comment]
Closing this, as I have mostly been tracking things per eprime language, not minion constraint.
