### ISSUE TITLE
Implement regression testing and performance testing in CI

### ISSUE THREAD

**Issue by gskorokhod** [conjure-cp/conjure-oxide#247]
Currently, our integration tests verify that a model has been parsed and rewritten correctly, get Minion solutions, and validate them against a hard coded correct set of solutions.

# Overview

Instead, we need to run the same model through `conjure-oxide` and `conjure` proper, and compare their solutions, as well as various performance metrics (for now, probably just the CPU time it takes to solve).
This will achieve regression testing ("our solution is not different from old conjure, which is assumed to be correct") and performance testing (measuring how much worse (or better!) our performance is compared to conjure)

# Tasks

- [ ] Expand out script that installs conjure to also install solvers
- [ ] Read conjure docs to find a way to get performance information and metadata out of it
- [ ] Write code to parse the solution that conjure gives us and the metadata mentioned above 
- [ ] Expand our CI to compare our solution and our performance to conjure 

As a separate task, we would probably need a nice web page to visualise the results of performance testing. 
This will be a separate issue
