### ISSUE TITLE
Tracking issue for: Native Essence parser

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/conjure-oxide#464]
- [x]  introduce a new function called `parse_essence_file_native` - this should have the same interface as the existing [parse_essence_file function](https://github.com/conjure-cp/conjure-oxide/blob/85b2e45b6163cb4feac4a462695379541f60f70d/conjure_oxide/src/utils/conjure.rs#L44)
- [x] #465
- [x] add a step 0 before 1 to integration testing ([see](https://github.com/conjure-cp/conjure-oxide/blob/85b2e45b6163cb4feac4a462695379541f60f70d/conjure_oxide/tests/generated_tests.rs#L110)). this should parse the model using the native parser. treat this as the generated model. compare against expected model. for the rest of the file, we should continue to use the astjson parser
- [x]  make step 0 conditional. use the config.toml file for this, by adding `skip_native_parser=true` to the file. this can be implemented by adding a new field to the struct [here](https://github.com/conjure-cp/conjure-oxide/blob/85b2e45b6163cb4feac4a462695379541f60f70d/conjure_oxide/tests/generated_tests.rs#L33)

_Originally posted by @ozgurakgun in https://github.com/conjure-cp/conjure-oxide/issues/392#issuecomment-2483362251_

**Comment by ozgurakgun** [comment]
I think all of these are done @leiamcalisteryoung, closing.

**Comment by ozgurakgun** [comment]
Maybe you can create a new "tracking issue" for the remaining work once #392 is merged.
