### ISSUE TITLE
Implement negation and negated sums

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#490]
## Description

Implement negated literals and negated sums, including expressions of the form:

* `-x = y`   _(minus equals)_
* `x / (-y / z) = a`   _(negated atoms)_
* `x + y -z - (x + 3`) = a.  _(sums with negatives)_

## Tasks

- [x] Move arithmetic normalizers into their own file
- [x] Implement `-(-x) ~> x` _(double negation)_ 
- [x] #497
- [x] Implement `-x = y ~> mineq(M,N)` _(mineq_introduction)_
- [x] Implement flattening rule `-x ~> aux0 where aux0 -= x`   _(negation flattening)_ 
- [x] #489 
- [ ] #553

**Comment by niklasdewally** [comment]
@ozgurakgun Do we want to call them simplifiers / simplification rules in Oxide (like Savile Row) or horizontal rules?

**Comment by ozgurakgun** [comment]
They are called simplifiers or partial evaluators in Conjure too. Horizontal rules are something else.

**Comment by ozgurakgun** [comment]
Actually what you describe here is different, sorry. I would call them normalisers. They put expressions in a normal form.

**Comment by niklasdewally** [comment]
@ozgurakgun question about the Conjure parser:

This parses as a `MkOpMinus` operator:

```
language ESSENCE' 1.0
$ convert sums using weightedsumgeq + weightedsumleq

find x: int(1..3)
find y: int(-1..1)
find z: int(-1..1)
such that x = (-y + z)
```

This parses as a `MkOpSum` of the negation of `y`:

```
language ESSENCE' 1.0
$ convert sums using weightedsumgeq + weightedsumleq

find x: int(1..3)
find y: int(-1..1)
find z: int(-1..1)
such that x = (z - y)
```

Can I treat these the same semantically?

---

I think the normal form for this should be sums of negated atoms as opposed to using minuses and arbitrary nested expressions. Similar idea to negation normal form for booleans.

```
1. (a - b) ~> a+b
2.  -(a + b) ~> -a -b 
3. --x ~> x
```

Once stated as sums, we can do associativity and commutativity on them (remove nesting, order the variables, etc), which helps put them in a canonical ordering and format.

**Comment by niklasdewally** [comment]
Just as in logic we make NNF into a "canonical form" by turning it into CNF / DNF by applying distributivity in a certain direction, we could go from our ordered flat sums into a canonical form by applying distributivity of  + and *?

The second step isn't necessary here, but getting to NNF-equivalent would be very worth it due to the partial evaluation potential it brings.

**Comment by ozgurakgun** [comment]
Makes sense to me. They should definitely normalise to the same thing.
