### ISSUE TITLE
Implement identity, binary operator, and skipping operator for associative commutative operators

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#493]
## Description

For every AC operator we could have a triplet defined: identity, binary operator, skipping operator. The first two are hopefully clear, the third is a bit weird but useful. 

Let's take sum as an example. 0 is the identity, + is the binop, `\ (b, x) -> toInt(b) * x` is the skipping operator. 

Skipping op evaluates to identity if b is false, to the second argument if b is true. 

For logical and it is `\ (b, x) -> b => x`

For logical or it is `\ (b, x) -> b /\ x`

_Originally posted by @ozgurakgun in https://github.com/conjure-cp/conjure-oxide/issues/491#issuecomment-2500920151_

## Tasks

- [x] #494 
- [ ] Implement identity function for AC operators
- [ ] Implement binop function for AC operators
- [ ] Implement skipping op function for AC operators

**Comment by niklasdewally** [comment]
This will become useful later when I get to quantifiers and comprehensions.
