### ISSUE TITLE
Tracking issue: Essence features wanted for Randicheck

### ISSUE THREAD

**Issue by TAswan** [conjure-cp/conjure-oxide#510]
- [x] #511
- [x] #512
- [ ] Functions (alternatively what does the E' for this look like?)
- [ ] Defined (attached to functions)
- [ ] Branching on (not essential but nice to have)
- [ ] Enums (also not essential, using integers is fine for current usecase)

@niklasdewally
