### ISSUE TITLE
Implement `letting`

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/conjure-oxide#512]
Add `letting`  declarations.

Instead of just storing decision variables, let the symbol table be of type:

```rs
SymbolTable<Name,RefTo>
```

where RefTo is an enum:

```rs
enum RefTo {
  Letting(Letting),
  DecisionVariable(DecisionVariable),
 // and so on
 }
```
## To-do

- [x] #522
- [ ]  Parse`letting` declarations (json)
- [ ]  Parse`letting` declarations (tree-sitter) 
- [ ] Rule to substitute lettings for their values before passing to Minion.
