### ISSUE TITLE
Chuffed Bindings

### ISSUE THREAD

**Issue by Kieranoski702** [conjure-cp/conjure-oxide#8]
The purpose of this issue is to plan, document, and track the development of the chuffed bindings.

Any comments and feedback would be appreciated.

# Plan
## Introduction

As part of this project, we aim to provide native Rust interfaces to solvers. Currently, plain text is used to pass information between Conjure, Savile Row, and the underlying solvers. This is bad for performance, especially when many passes of a solver are being run.

Chuffed is run primarily through public API functions found within `libchuffed.a`. 

My aim for the Chuffed bindings is to implement the functionality of the API functions found within `libchuffed.a` as Rust APIs.

The plan is to link `libchuffed.a` and create bindings for the functions contained within, then create wrapper functions where necessary to "convert" the functions to be more rust-like (using rust types, conventions, safety, etc). We should then be able to use these functions to create some examples (such as solving a sudoku puzzle)

## Tasks

- [X] Create bindings by linking `libchuffed.a`
- [ ] Create wrapper functions for core functions
- [ ] Create a Sudoku (or similar) example
- [ ] Expand wrapper functions/Rust API as much as possible

**Comment by Kieranoski702** [comment]
#6

**Comment by Kieranoski702** [comment]
The initial binding and linking can be found in PR #6

**Comment by niklasdewally** [comment]
#9

**Comment by niklasdewally** [comment]
@ozgurakgun closing
